project:
  type: website
  output-dir: docs

website:
  title: "Open Urban Air and Meteorological Data"
  site-url: https://jcaceres-academic.github.io/OpenUrbanAirandMeteorological/index.html
  description: "Citizen Science and STEM Education with R"
  page-navigation: true
  search: false
  navbar:
    background: "#7A0026"
    pinned: true        # ðŸ”’ mantiene la barra fija al hacer scroll
    right:
      - icon: house 
        text: "Home"
        href: index.html
        target: "_self"
      - icon: file-earmark-text
        text: "Article"
        href: article.pdf
        target: "_blank"   # ðŸ”— abre el PDF en una pestaÃ±a nueva
      - icon: laptop
        text: "Notebook"
        href: notebook.html
        target: "_self"
      - icon: github
        text: "GitHub"
        href: https://github.com/jcaceres-academic/OpenUrbanAirandMeteorological
        target: "_blank"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "On this page"
    toc-depth: 2
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    number-sections: false
    lang: en
    html-math-method: mathjax

editor: visual


