project:
  type: website
  output-dir: docs

website:
  title: "Behavioural and Institutional Drivers of Green Technology Adoption"
  site-url: https://jcaceres-academic.github.io/extended-tam-green-technology/
  description: "An Extended Technology Acceptance Model Framework for Sustainability Transitions"
  page-navigation: true
  search: false
  navbar:
    background: "#7A0026"
    pinned: true        # ðŸ”’ mantiene la barra fija al hacer scroll
    right:
      - icon: house
        text: "Home"
        href: index.html
      - icon: file-earmark-text
        text: "Article"
        href: article.pdf
        target: "_blank"
      - icon: laptop
        text: "Notebook"
        href: notebook.html
      - icon: journal-text
        text: "Zenodo"
        href: https://doi.org/10.5281/zenodo.18415073
        target: "_blank"
      - icon: github
        text: "GitHub"
        href: https://github.com/jcaceres-academic/extended-tam-green-technology
        target: "_blank"

format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true
    toc-location: left
    toc-title: "On this page"
    toc-depth: 2
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    number-sections: false
    lang: en
    html-math-method: mathjax

editor: visual


